# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "v4l2loopback" "snd_aloop" "uinput" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/397fcf44-2458-4014-8e38-32255fa4b443";
    fsType = "btrfs";
    options = [ "subvol=nixos/@" "compress=zstd" "ssd" ];
  };

  boot.initrd.luks.devices."root".device =
    "/dev/disk/by-uuid/0b88f4ac-70ed-442b-b43e-ffd703b9cf8d";

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/397fcf44-2458-4014-8e38-32255fa4b443";
    fsType = "btrfs";
    options = [ "subvol=nixos/@home" "compress=zstd" "ssd" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/397fcf44-2458-4014-8e38-32255fa4b443";
    fsType = "btrfs";
    options = [ "subvol=nixos/@nix" "compress=zstd" "ssd" "noatime" ];
  };

  fileSystems."/efi" = {
    device = "/dev/disk/by-uuid/DFC6-AEF9";
    fsType = "vfat";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/69ddab2e-2c16-4b3a-8d6a-288babc26329";
    fsType = "btrfs";
    options = [ "subvol=nixos" ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
}

