#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

hc emit_hook reload

nitrogen --restore &
conky &

# Uncomment the following lines to use xmobar as the panel
# Remember to comment out the last 8 lines of this config, so that
# polybar will no longer launch on startup.
# $HOME/.config/herbstluftwm/xmobar

# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Mod4                            # Use the super key as the main modifier.
appMod=Mod1                         # Use the alt key as the aplication modifier.
myTerm=alacritty                    # Set my preferred terminal.
myEditor="emacsclient -c -a emacs"  # Set my preferred editor.
myIrcClient="emacsclient -c -a emacs -e (erc)"  # Set my preferred irc client.
myConfigEditor="emacsclient -e (keo/new-config-frame)"  # Set my preferred editor for editing configs.
myEmacsConfigCommand="emacsclient -e (keo/wm-open-config \"emacs\")" 
myHerbstluftConfigCommand="emacsclient -e \"(keo/wm-open-config \\\"herbstluft\\\")\"" 
myBrowser=firefox  # Set my preferred web browser.
myScratchpadCommand=~/.config/herbstluftwm/scratchpads.sh
~/.config/herbstluftwm/scratchpads.sh term-scratchpad
~/.config/herbstluftwm/scratchpads.sh spotify-scratchpad

hc spawn ~/.config/herbstluftwm/exec_on_tag.sh spotify-scratchpad spotify
hc spawn ~/.config/herbstluftwm/exec_on_tag.sh term-scratchpad $myTerm

hc keybind $Mod-Shift-e quit
hc keybind $Mod-r reload
hc keybind $Mod-q close
hc keybind $Mod-Return spawn $myTerm
hc keybind $appMod-Control-Return spawn  ./xmenu/xmenu.sh
hc keybind $Mod-t spawn slock
hc keybind $Mod-n spawn emacsclient -e "(keo/wm-switch-window)"
hc keybind $appMod-p spawn emacsclient -e "(keo/wm-open-project)"
hc keybind $appMod-k spawn xdotool type "2K\@5246\%\$3\#\@2\$\$24k"

~/.config/herbstluftwm/keychords/dired.sh
~/.config/herbstluftwm/keychords/config.sh
~/.config/herbstluftwm/keychords/scratchpad.sh
~/.config/herbstluftwm/keychords/web.sh
~/.config/herbstluftwm/keychords/media.sh
~/.config/herbstluftwm/keychords/ssh.sh

# Start rofi
hc keybind $Mod-d spawn rofi -show run

# Open clipmenu
hc keybind $appMod-c spawn CM_LAUNCHER=rofi clipmenu

# Open emoji selector
hc keybind $Mod-x spawn rofi -modi emoji -show emoji -kb-custom-1 Ctrl+C

# Open bluetooth
hc keybind $Mod-b spawn rofi-bluetooth

# Open rofi calculator
hc keybind $Mod-u spawn rofi -show calc -modi calc -no-show-match -no-sort

# My dmenu scripts (Alt+Ctrl+Key)
hc keybind $appMod-Control-p spawn passmenu
hc keybind $appMod-Control-w spawn ./.rofi/rofi-windowmenu.sh

# My applications (Alt+Key)
hc keybind $appMod-i spawn $myIrcClient
hc keybind $appMod-e spawn $myEditor
hc keybind $appMod-u spawn urxvt
hc keybind $appMod-s spawn flameshot gui
hc keybind $appMod-d chain \
      '->' spawn pkill -9 Discord \
      '->' spawn discord
hc keybind $appMod-q spawn spotify
hc keybind $appMod-n spawn $myBrowser

# My games (Alt+Shift+Key)
hc keybind $appMod-Shift-m spawn prismlauncher
hc keybind $appMod-Shift-d spawn launch-doom

# focusing clients
hc keybind $Mod-h             focus left
hc keybind $Mod-j             focus down
hc keybind $Mod-k             focus up
hc keybind $Mod-l             focus right
                              
# moving clients              
hc keybind $Mod-Shift-h       shift left
hc keybind $Mod-Shift-j       shift down
hc keybind $Mod-Shift-k       shift up
hc keybind $Mod-Shift-l       shift right

# splitting frames
hc keybind $Mod-b             split  bottom  0.5
hc keybind $Mod-v             split  right   0.5
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-h      resize left +$resizestep
hc keybind $Mod-Control-j      resize down +$resizestep
hc keybind $Mod-Control-k      resize up +$resizestep
hc keybind $Mod-Control-l      resize right +$resizestep

# tags
tag_names=("mus" "dev" "sys" "www" "vbox" "chat" "mus" "vid" "gfx" "config")
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-i jumpto urgent

# theme
~/.config/herbstluftwm/currentTheme.sh
# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule class=VirtualBox tag=5 # move all VMs to tag 5
hc rule title='Oracle VM VirtualBox Manager' tag=5 
hc rule class=VirtualBox pseudotile=on
hc rule class=VirtualBox fullscreen=on
hc rule instance=mpvFullscreen fullscreen=on
hc rule instance=swallow hook=swallow
hc rule instance=Emacs-Config floating=on floatplacement=center
hc rule instance=Emacs-Dired floating=on floatplacement=center
hc rule instance=Config class=Emacs tag=config
for i in "${my_array[@]}"; do exec $(echo $i | tr -d '"'); done
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc detect_monitors
#hc set_monitors 2560x1440+0+0

# start the panel
hc spawn polybar i3-panel --reload &
hc spawn $myConfigEditor
